### ISSUE TITLE
feat: allow controlling the display order of `coder-parameters` 

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coder#103]
Currently, the order of `coder_parameter`s seems to be alphabetical. Could you allow control of the display order?

**Comment by dcarrion87** [comment]
+1 for this. Is there a work around to order input parameters. It almost seems completely random. I can't seem to even trick it so they're alphabetical.

E.g. Why would ray_worker_max_replicas appear above instance_type in the UI?

data "coder_parameter" "ray_image" {
  name        = "Ray Docker Image"
  mutable     = true
  type        = "string"
  description = "Docker image used for the Ray head and workers"
  default     = "rayproject/ray-ml:2.2.0-py38-cu116"
}


data "coder_parameter" "instance_type" {
  name        = "Instance Type"
  description = "Select an instance type"
  mutable     = true
  type        = "string"
...
}

data "coder_parameter" "ray_worker_max_replicas" {
  name        = "Maximum Worker Replicas"
  description = "Number of worker replicas that can dynamically be created"
  mutable     = true
  type        = "number"
  default     = 1
}

**Comment by matifali** [comment]
This seems to be fixed now and order can be controlled by setting the `name` alphabetically
