### ISSUE TITLE
bug: .svg urls do not display in `coder_parameter`s `icon` property 

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coder#105]
# Description 
While setting the `icon` property of the `coder_paramter` and nested `option` field, SVG logos hosted on a publically accessible CDN do not work. PNG logos are working fine.
# Problem
## Does not work
```hcl
icon = "https://github.com/matifali/coder/blob/ml-logos/site/static/icon/jax.svg"
```
## Works
1. png cdn urls
	```hcl
	icon = "https://github.com/matifali/coder/blob/ml-logos/site/static/icon/gcp.png"
	```
2. logos included with Coder.
	```hcl
	icon = "/icon/jupyter.svg"
	icon = "/icon/gcp.png"
	```
# Context
Also, support using the logos included in the template directory. related https://github.com/coder/coder/issues/6339

**Comment by matifali** [comment]
cc: @mtojek

**Comment by mtojek** [comment]
When you use a link like `https://github.com/matifali/coder/blob/ml-logos/site/static/icon/jax.svg`, you will see this error in the browser console:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/matifali/coder/blob/ml-logos/site/static/icon/jax.svg with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

It isn't related to Coder parameters, but security policies. Please try to use the _raw_ link:

```
https://raw.githubusercontent.com/matifali/coder/ml-logos/site/static/icon/jax.svg
```

Hint: if you want to link to GitHub resources, always pick the raw links.

**Comment by matifali** [comment]
Thanks, @mtojek. I will try and update you.

**Comment by matifali** [comment]
This works when we use raw URLs.
You may close or implement allowing using local icons functionalityhttps://github.com/coder/coder/issues/6339
