### ISSUE TITLE
feat: Parse `coder_metadata` resource `item` as markdown

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coder#115]
https://registry.terraform.io/providers/coder/coder/latest/docs/resources/metadata#nested-schema-for-item

```hcl
resource "coder_metadata" "workspace_info" {
  count       = data.coder_workspace.me.start_count
  resource_id = docker_image.deeplearning.id
  icon        = data.coder_parameter.framework.option[index(data.coder_parameter.framework.option.*.value, data.coder_parameter.framework.value)].icon
  item {
    key   = "Framework"
    value = data.coder_parameter.framework.option[index(data.coder_parameter.framework.option.*.value, data.coder_parameter.framework.value)].name
  }
  item {
    key   = "NGC Version"
    value = local.ngc-version
	link = 'https://some-link.com'  
  }
  item {
    key   = "CPU Cores"
    value = data.coder_parameter.cpu.value
  }
  item {
    key   = "RAM (GB)"
    value = data.coder_parameter.ram.value
  }
}
```

**Comment by matifali** [comment]
What do you think about this?@bpmct

**Comment by bpmct** [comment]
What if we rendered markdown in the value?

**Comment by matifali** [comment]
That would do the purpose; This is my idea if we can somehow make the values clickable and can open links. Nice idea

**Comment by matifali** [comment]
As a workaround, an external `coder_app` resource can be used.

**Comment by hh** [comment]
Got my vote!

**Comment by matifali** [comment]
@coder/ts how difficult is it to support markdown for rendering [`values`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/metadata#value) field?

**Comment by BrunoQuaresma** [comment]
The difficult part is not the implementation but how to make it looks nice

**Comment by matifali** [comment]
Can't we simply render the text as markdown? For example
```md
[Google](https://google.com)
``` 
Should render as [Google](https://google.com)

**Comment by aslilac** [comment]
![Image](https://github.com/coder/terraform-provider-coder/assets/418348/98ccb0fc-5aba-4344-8f0a-12595273218e)

rendering it as markdown is trivial. this took me like 15 minutes. but it's also pretty weird to just have this sort of stuff be possible. 😅

![Image](https://github.com/coder/terraform-provider-coder/assets/418348/fedf80fb-4932-4ad5-8c77-abb8849303c7)

there's also the fact that we currently support "click to copy", which makes a lot less sense when the description is more complex markdown, and interferes with clicking links.

**Comment by matifali** [comment]
I agree markdown could be pretty  complex, the original request was to just be able to create hyperlinks. For example if we show the version of a software then clicking it could open a URL to the changelog.

**Comment by aslilac** [comment]
I think we just need to come up with the right way to describe them. maybe we could restrict these to a subset of markdown somehow? and probably someway to detect whether it's markdown or not so we know whether to make it copyable or not. idk if we expose that in the terraform provider or if we just try to be smart about it.

**Comment by aslilac** [comment]
we could limit it to a __super__ strict subset of markdown that basically only allows a single like and nothing else

**Comment by matifali** [comment]
SGTM, I do not have any other use case in mind. Maybe @bpmct can think of one.
I think a minimal markdown support with the ability to bold and hyperlink text would be enough.
