### ISSUE TITLE
Feature Request: Add `coder_env` Resource for Injecting Environment Variables into Workspaces

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coder#170]
## Resource Name
`coder_env`

### Description
This feature would introduce a new resource, `coder_env`, to the Coder Terraform provider, allowing users to inject environment variables dynamically into workspaces at creation and update.

## Expected Behavior
- Enable defining environment variables in the Terraform configuration file using `coder_env`.
- Inject environment variables into the workspace specified by the `agent_id`.

## Use Case
Automating workspace setups to include necessary environment variables is essential for preparing development environments with all the configurations needed for applications and services to function correctly. An example use case is configuring go to use Artifactory, which requires setting `GOPROXY`.

### Single variable
```hcl
resource "coder_env" "example" {
  agent_id = coder_agent.example.id
  name     = "VAR1"
  value    = "Value1"
}
```
### Multiple variables
```hcl
resource "coder_env" "example" {
  agent_id = coder_agent.example.id
  item {
    name     = "VAR1"
    value    = "Value1"
  }
  item {
    name     = "VAR2"
    value    = "Value2"
  }
```
or
```hcl
resource "coder_env" "example" {
  agent_id = coder_agent.example.id
  env = {
	VAR1 = "value1"
	VAR2 = "value2"
  }
}
```

**Comment by mafredri** [comment]
What's the benefit over using `env` property on agent? https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#env

**Comment by matifali** [comment]
@mafredri `coder_script` does not have an env block. So if we want a module to inject a new env variable, we need either to add `env` to `coder_script` or have `coder_env`

**Comment by mafredri** [comment]
Ah, that makes sense, sgtm!
