### ISSUE TITLE
feat: `coder_parameter` support support masked fields for things like access_keys and passwords

### ISSUE THREAD

**Issue by michaelbrewer** [coder/terraform-provider-coder#207]
`coder_parameter` already supports [ephemeral](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter#ephemeral) but it would help to also have a setting to mask or hide parameters.

**Comment by matifali** [comment]
Related to #194

**Comment by michaelbrewer** [comment]
will track that issue
