### ISSUE TITLE
Coder Terraform Provider v1.0 Docs 

### ISSUE THREAD

**Issue by stirby** [coder/terraform-provider-coder#217]
Customers have requested that we promote our terraform provider to `v1.0`. The product is quite stable and, of course, is used in every one of our customers' deployments. 

To show that this is no longer breaking, we should promote the release versioning to `v1.X.X`; before we do so, the [docs](https://registry.terraform.io/providers/coder/coder/latest/docs) should meet `v1.0` standards. As I mentioned, we don't get many stability requests, but there are often requests for elaboration on the provider's behavior. There are a few resources/data sources that are missing code examples, or may be enriched via context.

### Docs checklist for v1.0 
- [x] Resource docs
  - [x] [`coder_env`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/env)
    - [x] Code examples
  - [x] [`coder_script`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/script)
    - [x] Code examples
    - [x] Explanation on parallel execution 
    - [x] ~Startup script implications~
    - [x] ~Link to discussion on [execution ordering](https://github.com/coder/coder/issues/10352) (frequently requested)~
      - not necessary 
- [x] Data source docs
  - [x] [`coder_external_auth`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/external_auth)
    - [x] Code examples
    - [x] Link to coder.com external auth docs
  - [x] [`coder_parameter`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter)
    - [x] Code examples (show validation types, monotonicity, etc)
      - Should just grep the closed customer requests on `coder_parameter` ([like this](https://github.com/coder/customers/issues?q=is%3Aissue+is%3Aclosed+coder_parameter+)) 
    - [x] https://github.com/coder/terraform-provider-coder/issues/242
    - [x] Optional: Fix inline link under `icon`
    - [x] ~Optional: Link to discussion on coder_parameter extension~
  - [x] [`coder_provisioner`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/provisioner)
    - [x] Code example
    - [x] Optional: Fix inline links
  - [x] [`coder_workspace`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace)
    - [x] ~Optional: Expand code examples~
      - Not enough attributes to warrant further examples  
  - [x] [`coder_workspace_owner`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace_owner)
    - [x] Code examples
- [x] https://github.com/coder/coder/discussions/13122 - indicate required version of coder for resource functionality
- [x] #224  
- [x] #222
- [x] #237
- ~[ ] #250~
- [ ] #260

**Comment by stirby** [comment]
A candidate to further improve the docs here:
https://github.com/coder/coder/discussions/13122

**Comment by matifali** [comment]
Yes we should mention the minimum required coder version on the main page of provider docs for each release.

**Comment by matifali** [comment]
Before realizing 1.0, we should do migration #180. Otherwise, it will stay a debt.

**Comment by bpmct** [comment]
https://github.com/coder/envbuilder/pull/174#discussion_r1591093964 a good idea to add a new `coder_user` data source and deprecate the `owner_` stuff

**Comment by matifali** [comment]
@bpmct filed #219 and #220

**Comment by stirby** [comment]
> Before realizing 1.0, we should do migration https://github.com/coder/terraform-provider-coder/issues/180. Otherwise, it will stay a debt.

@matifali I understand the motivation here, but do not want to block `v1.0` for the migration. I would even call this a candidate for `v2.0`. I'd rather rush these documentation changes + any minor changes and promote the versioning for the comfort of our customers. 

If this unblocks feature development today, we can discuss.  

For posterity
> We recommend using the [framework](https://developer.hashicorp.com/terraform/plugin/framework) to develop new provider functionality because it offers significant advantages as compared to the SDKv2. We also recommend migrating existing providers to the framework when possible.
- [List of benefits from migration](https://developer.hashicorp.com/terraform/plugin/framework/migrating/benefits)

**Comment by matifali** [comment]
@stirby Sure, let's do that in v2.0, then. How demanding would the migration would be?

Additionally, as per https://endoflife.date/go, only the latest 2 versions of Go are supported for any security patches. `terraform-terraform-coder` is on 1.20, which has been unsupported for the last 3 months. So, we probably should consider bumping the go version to 1.22.

**Comment by stirby** [comment]
I am re-opening since we need to cut the `v1.0`

**Comment by matifali** [comment]
@stirby I think we should resolve #203 too before we cut the 1.0 release. 

It doesn't matter if we are removing all deprecated items.
