### ISSUE TITLE
Add `coder_workspace_owner` data source

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coder#219]
Extracted from https://github.com/coder/envbuilder/pull/174#discussion_r1591093964

The properties that are per user and not per workspace should be added/refactored to the new data source, `coder_user`. 

Other properties that should be added or moved from `coder_workspace` can be

1. `coder_workspace.owner` -> `coder_user.name`
2. `coder_workspace.owner_name` -> `coder_user.full_name`
3. `coder_workspace.owner_emial` -> `coder_user.email`
4. Add `coder_user.private_ssh_key` ([sensitive](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes/string#sensitive))
5. Add `coder_user.public_ssh_key`
6. Add `coder_user.groups` (A list of all groups if applicable)

**Comment by johnstcn** [comment]
Wrinkle: "groups" can apparently contain any arbitrary data, which is going to be a headache.

**Comment by johnstcn** [comment]
Wrinkle: we'll also need to send this information from Coder (separate issue)

**Comment by johnstcn** [comment]
For the sake of clarity, this datasource will instead be named `coder_workspace_owner` as it will refer to information about the workspace owner and not the user creating the workspace.

**Comment by johnstcn** [comment]
Part 1 is here: https://github.com/coder/terraform-provider-coder/pull/230

**Comment by matifali** [comment]
There is a related request to expose the user's timezone settings in #213.

Additionally, we can expose account type, i.e., `password`, `github`, `oidc`, or `none` (could be extracted to a new issue)
![image](https://github.com/coder/terraform-provider-coder/assets/10648092/58097426-aed9-4f80-bcf9-75e8ab7358c0)

**Comment by johnstcn** [comment]
https://github.com/coder/coder/pull/13366 updates Coder to allow passing the new fields.
