### ISSUE TITLE
bump go version

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coder#222]
Extracted from https://github.com/coder/terraform-provider-coder/issues/217#issuecomment-2102217213

As per https://endoflife.date/go, only the latest 2 versions of Go are supported for any security patches. `terraform-terraform-coder` is on 1.20, which has been unsupported for the last 3 months. So, probably should consider bumping the go version to 1.22.

**Comment by johnstcn** [comment]
cc @mtojek -- candidate for between-sprints?

**Comment by mtojek** [comment]
definitely
