### ISSUE TITLE
Improve version compatibility

### ISSUE THREAD

**Issue by ammario** [coder/terraform-provider-coder#224]
In https://github.com/coder/coder/discussions/13122 a user sees empty values when referencing `${data.coder_workspace.me.template_id}` in their template. This happens because their coder server version is behind the provider, and this kind of issue will continue to appear as we implement more provider functionality (https://github.com/coder/terraform-provider-coder/issues/220, #219).

There are two things we should do to fix this:

1. In our docs under each attribute and resource, declare the Coder version requirements

2. Replace code like:
https://github.com/coder/terraform-provider-coder/blob/3cc9802d8c2ac8a6254b1c7242fbc9e19756bc46/provider/workspace.go#L83-L90

with `LookupEnv` and _fail_ the build when a value is missing instead of using blanks.

**Comment by johnstcn** [comment]
As an extra check, we could pass in the Coder version to the provisioner, and then check the version against the oldest version of Coder supported by the provisioner. WDYT?

**Comment by ammario** [comment]
> As an extra check, we could pass in the Coder version to the provisioner, and then check the version against the oldest version of Coder supported by the provisioner. WDYT?

I think passing the version is a good idea, but I think we should add rules to convert old parameters into new ones instead of "breaking" at certain version boundaries.

We want to minimize upgrade anxiety caused by breakage.

**Comment by mtojek** [comment]
`SchemaVersion` has been merged.

Next steps:

> Coder provisioner uses terraform-plugin-coder in different contexts - a dry run, a template run, a workspace build, etc. We can't use helpers.RequireEnv() in other modes than "workspace build", as the provisioner does not set these values (empty variable). If we switch to helpers.RequireEnv() now, "template import" will fail due to unset env values.
We can implement a workaround by passing the extra env variable CODER_WORKSPACE_BUILD_ID=.... If this variable is set, the plugin should presence the required env values.
