### ISSUE TITLE
feat: add login_type to coder_workspace_owner data source

### ISSUE THREAD

**Issue by johnstcn** [coder/terraform-provider-coder#235]
...we can expose account type, i.e., `password`, `github`, `oidc`, or `none` (could be extracted to a new issue) [https://github.com/coder/terraform-provider-coder/assets/10648092/58097426-aed9-4f80-bcf9-75e8ab7358c0](https://github.com/coder/terraform-provider-coder/assets/10648092/58097426-aed9-4f80-bcf9-75e8ab7358c0)

_Originally posted by @matifali in _ [_https://github.com/coder/terraform-provider-coder/issues/219#issuecomment-2135511772_](https://github.com/coder/terraform-provider-coder/issues/219#issuecomment-2135511772)

**Comment by pmareke** [comment]
Hi, is this issue still open?

**Comment by johnstcn** [comment]
> Hi, is this issue still open? I would like to give it a try.

Yes, this issue has not yet been worked on!

**Comment by pmareke** [comment]
Great, done!

**Comment by matifali** [comment]
Hi @pmareke thank your for your contribution. Could you run `make gen` to let the linter pass?

**Comment by pmareke** [comment]
Done!

**Comment by pmareke** [comment]
> Hi @pmareke thank your for your contribution. Could you run `make gen` to let the linter pass?

Done!

**Comment by johnstcn** [comment]
https://github.com/coder/terraform-provider-coder/pull/287 updates the provider to add the field. A separate PR will be required in `coder/coder` to set `CODER_WORKSPACE_OWNER_LOGIN_TYPE`.

**Comment by pmareke** [comment]
Thanks so much @johnstcn, I really like doing the PR!

**Comment by dannykopping** [comment]
> [#287](https://github.com/coder/terraform-provider-coder/pull/287) updates the provider to add the field. A separate PR will be required in `coder/coder` to set `CODER_WORKSPACE_OWNER_LOGIN_TYPE`.

@johnstcn do you know if there was a subsequent PR raised for this?
Right now the provider just raised a warning each time: `Warning: WARNING: The CODER_WORKSPACE_OWNER_LOGIN_TYPE env variable is not set`.

**Comment by johnstcn** [comment]
@dannykopping @matifali looks like it wasn't. I can add one quickly.
