### ISSUE TITLE
docs missing deprecation notice and migration steps

### ISSUE THREAD

**Issue by matifali** [coder/terraform-provider-coder#237]
Provider docs at registry.coder.com do not mention the deprecation of parameters. 

For example, multiple fields of `data.coder_workspace` were deprecated in `v0.23.0`, but the docs at https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace do not indicate any such information.

Additionally, when a resource is deprecated, the message should contain the new resource to be migrated to or a link to some migration guide both in Terraform logs and on the docs page.

**Comment by matifali** [comment]
related #203

**Comment by johnstcn** [comment]
Looks like you need to specify `DeprecationMessage` and not just `Deprecated`.
https://developer.hashicorp.com/terraform/plugin/framework/handling-data/schemas#deprecationmessage-1

**Comment by matifali** [comment]
Good find @johnstcn 🧠

**Comment by mtojek** [comment]
Ok, I researched the issue. It may not be a straightforward solution or, in other words, it could be easier to apply patch `.md` files.

The [docs generator](https://github.com/hashicorp/terraform-plugin-docs) strongly depends on `providers schema`:

<img width="1086" alt="Screenshot 2024-06-25 at 16 02 38" src="https://github.com/coder/terraform-provider-coder/assets/14044910/d6edd0e0-664f-4dd1-aaec-e846f615d702">... and the schema does not expose the deprecation message.

It would be hard/impossible to expose the message via the fork&modify approach, so my recommendation is to implement a script which will run after the hashicorp generator, and "patch" docs:

```
- `owner_email` (String, Deprecated) Email address of the workspace owner.
```

->

```
- `owner_email` (String, Deprecated: Use `coder_workspace_owner.email` instead.) Email address of the workspace owner.
```

@johnstcn @stirby Please let me know your thoughts 👍

**Comment by johnstcn** [comment]
Thanks for investigating! I think that's a perfectly valid workaround.
